/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TugasPosttest3;

/**
 *
 * @author Prayogo
 */
public class Tugas1 extends javax.swing.JFrame {

    /**
     * Creates new form Tugas1
     */
    public Tugas1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        PanelHOME = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        PanelMOBIL1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        PanelMOBIL2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        PanelMOBIL3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        PanelMOBIL4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        PanelMOBIL5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        MOBIL3 = new javax.swing.JButton();
        MOBIL4 = new javax.swing.JButton();
        MOBIL5 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        HOME = new javax.swing.JButton();
        MOBIL1 = new javax.swing.JButton();
        MOBIL2 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 255, 204));
        jPanel1.setLayout(new java.awt.CardLayout());

        PanelHOME.setBackground(new java.awt.Color(204, 255, 204));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel8.setText("\" DI SHORUM FKTI MENYEDIAKAN BERBAGI MOBIL MEWAH \"");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel9.setText("\" YANG DI JUAL ADALAH MOBIL - MOBIL KELAS \"");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel10.setText("\" YANG HARGANYA SANGAT MENGGIURKAN JOBA BISA DI LIHAT \"");

        javax.swing.GroupLayout PanelHOMELayout = new javax.swing.GroupLayout(PanelHOME);
        PanelHOME.setLayout(PanelHOMELayout);
        PanelHOMELayout.setHorizontalGroup(
            PanelHOMELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelHOMELayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelHOMELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelHOMELayout.createSequentialGroup()
                        .addGroup(PanelHOMELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10)
                            .addGroup(PanelHOMELayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(32, 32, 32)))
                        .addGap(81, 81, 81))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelHOMELayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(155, 155, 155))))
        );
        PanelHOMELayout.setVerticalGroup(
            PanelHOMELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelHOMELayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel8)
                .addGap(44, 44, 44)
                .addComponent(jLabel9)
                .addGap(35, 35, 35)
                .addComponent(jLabel10)
                .addContainerGap(115, Short.MAX_VALUE))
        );

        jPanel1.add(PanelHOME, "card2");

        PanelMOBIL1.setBackground(new java.awt.Color(255, 204, 204));

        jLabel3.setIcon(new javax.swing.ImageIcon("D:\\2.jpg")); // NOI18N

        javax.swing.GroupLayout PanelMOBIL1Layout = new javax.swing.GroupLayout(PanelMOBIL1);
        PanelMOBIL1.setLayout(PanelMOBIL1Layout);
        PanelMOBIL1Layout.setHorizontalGroup(
            PanelMOBIL1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMOBIL1Layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelMOBIL1Layout.setVerticalGroup(
            PanelMOBIL1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelMOBIL1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(57, 57, 57))
        );

        jPanel1.add(PanelMOBIL1, "card3");

        PanelMOBIL2.setBackground(new java.awt.Color(204, 204, 255));

        jLabel4.setIcon(new javax.swing.ImageIcon("D:\\3.jpg")); // NOI18N

        javax.swing.GroupLayout PanelMOBIL2Layout = new javax.swing.GroupLayout(PanelMOBIL2);
        PanelMOBIL2.setLayout(PanelMOBIL2Layout);
        PanelMOBIL2Layout.setHorizontalGroup(
            PanelMOBIL2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMOBIL2Layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelMOBIL2Layout.setVerticalGroup(
            PanelMOBIL2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMOBIL2Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(PanelMOBIL2, "card4");

        PanelMOBIL3.setBackground(new java.awt.Color(255, 0, 0));

        jLabel5.setIcon(new javax.swing.ImageIcon("D:\\4.jpg")); // NOI18N

        javax.swing.GroupLayout PanelMOBIL3Layout = new javax.swing.GroupLayout(PanelMOBIL3);
        PanelMOBIL3.setLayout(PanelMOBIL3Layout);
        PanelMOBIL3Layout.setHorizontalGroup(
            PanelMOBIL3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMOBIL3Layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelMOBIL3Layout.setVerticalGroup(
            PanelMOBIL3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelMOBIL3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(72, 72, 72))
        );

        jPanel1.add(PanelMOBIL3, "card5");

        PanelMOBIL4.setBackground(new java.awt.Color(0, 102, 102));

        jLabel6.setIcon(new javax.swing.ImageIcon("D:\\5.jpg")); // NOI18N

        javax.swing.GroupLayout PanelMOBIL4Layout = new javax.swing.GroupLayout(PanelMOBIL4);
        PanelMOBIL4.setLayout(PanelMOBIL4Layout);
        PanelMOBIL4Layout.setHorizontalGroup(
            PanelMOBIL4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelMOBIL4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel6))
        );
        PanelMOBIL4Layout.setVerticalGroup(
            PanelMOBIL4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMOBIL4Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(PanelMOBIL4, "card6");

        PanelMOBIL5.setBackground(new java.awt.Color(153, 0, 153));

        jLabel7.setIcon(new javax.swing.ImageIcon("D:\\6.jpg")); // NOI18N

        javax.swing.GroupLayout PanelMOBIL5Layout = new javax.swing.GroupLayout(PanelMOBIL5);
        PanelMOBIL5.setLayout(PanelMOBIL5Layout);
        PanelMOBIL5Layout.setHorizontalGroup(
            PanelMOBIL5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelMOBIL5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(67, 67, 67))
        );
        PanelMOBIL5Layout.setVerticalGroup(
            PanelMOBIL5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMOBIL5Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(PanelMOBIL5, "card7");

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setBackground(new java.awt.Color(153, 255, 102));

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 3, 36)); // NOI18N
        jLabel1.setText("SHORUM MOBIL - MOBIL MEWAH FKTI");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(jLabel1)
                .addContainerGap(102, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel3.setBackground(new java.awt.Color(51, 255, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 908, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_END);

        jPanel4.setBackground(new java.awt.Color(255, 51, 51));

        MOBIL3.setText("MOBIL 3");
        MOBIL3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MOBIL3ActionPerformed(evt);
            }
        });

        MOBIL4.setText("MOBIL 4");
        MOBIL4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MOBIL4ActionPerformed(evt);
            }
        });

        MOBIL5.setText("MOBIL 5");
        MOBIL5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MOBIL5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MOBIL3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(MOBIL4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(MOBIL5, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(MOBIL3)
                .addGap(46, 46, 46)
                .addComponent(MOBIL4)
                .addGap(41, 41, 41)
                .addComponent(MOBIL5)
                .addContainerGap(136, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4, java.awt.BorderLayout.LINE_END);

        jPanel5.setBackground(new java.awt.Color(255, 51, 255));

        HOME.setText("HOME");
        HOME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HOMEActionPerformed(evt);
            }
        });

        MOBIL1.setText("MOBIL 1");
        MOBIL1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MOBIL1ActionPerformed(evt);
            }
        });

        MOBIL2.setText("MOBIL 2");
        MOBIL2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MOBIL2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(HOME)
                    .addComponent(MOBIL1)
                    .addComponent(MOBIL2))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(HOME)
                .addGap(41, 41, 41)
                .addComponent(MOBIL1)
                .addGap(39, 39, 39)
                .addComponent(MOBIL2)
                .addContainerGap(136, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel5, java.awt.BorderLayout.LINE_START);

        jMenu1.setText("File");

        jMenuItem1.setText("jMenuItem1");
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HOMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HOMEActionPerformed
        // TODO add your handling code here:
        PanelHOME.setVisible(true);
        PanelMOBIL1.setVisible(false);
        PanelMOBIL2.setVisible(false);
        PanelMOBIL3.setVisible(false);
        PanelMOBIL4.setVisible(false);
        PanelMOBIL5.setVisible(false);
    }//GEN-LAST:event_HOMEActionPerformed

    private void MOBIL1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MOBIL1ActionPerformed
        // TODO add your handling code here:
          PanelHOME.setVisible(false);
          PanelMOBIL1.setVisible(true);
          PanelMOBIL2.setVisible(false);
          PanelMOBIL3.setVisible(false);
          PanelMOBIL4.setVisible(false);
          PanelMOBIL5.setVisible(false);
          
    }//GEN-LAST:event_MOBIL1ActionPerformed

    private void MOBIL2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MOBIL2ActionPerformed
        // TODO add your handling code here:
        PanelHOME.setVisible(false);
          PanelMOBIL1.setVisible(false);
          PanelMOBIL2.setVisible(true);
          PanelMOBIL3.setVisible(false);
          PanelMOBIL4.setVisible(false);
          PanelMOBIL5.setVisible(false);
    }//GEN-LAST:event_MOBIL2ActionPerformed

    private void MOBIL3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MOBIL3ActionPerformed
        // TODO add your handling code here:
        PanelHOME.setVisible(false);
          PanelMOBIL1.setVisible(false);
          PanelMOBIL2.setVisible(false);
          PanelMOBIL3.setVisible(true);
          PanelMOBIL4.setVisible(false);
          PanelMOBIL5.setVisible(false);
    }//GEN-LAST:event_MOBIL3ActionPerformed

    private void MOBIL4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MOBIL4ActionPerformed
        // TODO add your handling code here:
        PanelHOME.setVisible(false);
          PanelMOBIL1.setVisible(false);
          PanelMOBIL2.setVisible(false);
          PanelMOBIL3.setVisible(false);
          PanelMOBIL4.setVisible(true);
          PanelMOBIL5.setVisible(false);
    }//GEN-LAST:event_MOBIL4ActionPerformed

    private void MOBIL5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MOBIL5ActionPerformed
        // TODO add your handling code here:
        PanelHOME.setVisible(false);
          PanelMOBIL1.setVisible(false);
          PanelMOBIL2.setVisible(false);
          PanelMOBIL3.setVisible(false);
          PanelMOBIL4.setVisible(false);
          PanelMOBIL5.setVisible(true);
    }//GEN-LAST:event_MOBIL5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tugas1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tugas1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tugas1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tugas1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tugas1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton HOME;
    private javax.swing.JButton MOBIL1;
    private javax.swing.JButton MOBIL2;
    private javax.swing.JButton MOBIL3;
    private javax.swing.JButton MOBIL4;
    private javax.swing.JButton MOBIL5;
    private javax.swing.JPanel PanelHOME;
    private javax.swing.JPanel PanelMOBIL1;
    private javax.swing.JPanel PanelMOBIL2;
    private javax.swing.JPanel PanelMOBIL3;
    private javax.swing.JPanel PanelMOBIL4;
    private javax.swing.JPanel PanelMOBIL5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
}
